### ISSUE TITLE
[Chrome] SNS icons get closer on hover

### ISSUE THREAD

**Issue by huangginny** [huangginny/huangginny.github.io#3]
Chrome version 39.0
**Steps to reproduce**
Open the contact section
Hover over the five SNS icons, and make sure they turn gold on hover one by one...

**Expected**
The positions of those icons stay the same

**Actual**
They get closer to each other on hover. Google did not give me any useful solution...

**Comment by mekomlusa** [comment]
Positions of the icons stay the same with mouse hover over, but the background color is now deep blue instead of gold. Tested under Chrome Version 71.0.3578.98.

**Comment by huangginny** [comment]
> Positions of the icons stay the same with mouse hover over, but the background color is now deep blue instead of gold. Tested under Chrome Version 71.0.3578.98.

That's intentional... @mekomlusa
